version: '2'

services:
    nginx:
        restart: always
        image: nginx:1.11.6-alpine
    postgres:
        restart: always
        image: postgres:9.5.4
        expose:
            - 5432
        volumes:
          - ./docker/postgres/data:/var/lib/postgresql
    redis:
        restart: always
        image: redis:3.2.5-alpine
        expose:
          - 6379
        volumes:
          - ./docker/redis/data:/data
    django:
        restart: always
        build:
            context: .
            dockerfile: ./docker/django/Dockerfile
        volumes:
            - .:/django
    web:
        restart: always
        build:
            context: .
            dockerfile: ./docker/web/Dockerfile
        volumes:
            - .:/django
