version: '2'

services:
    nginx:
        extends:
            file: docker-common.yml
            service: nginx
        ports:
            - 8000:8000
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - backend
    postgres:
        extends:
            file: docker-common.yml
            service: postgres
        ports:
            - 5433:5432
        volumes:
            - ./docker/postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    redis:
        extends:
            file: docker-common.yml
            service: redis
    backend:
        extends:
            file: docker-common.yml
            service: django
        links:
            - postgres
        entrypoint:
            - /backend-entrypoint.sh
        expose:
            - 8000
    frontend:
        extends:
            file: docker-common.yml
            service: web
        links:
            - backend
        entrypoint:
            - /web-entrypoint.sh
    worker:
        extends:
            file: docker-common.yml
            service: django
        links:
            - redis
            - postgres
        entrypoint:
            - /worker-entrypoint.sh
    scheduler:
        extends:
            file: docker-common.yml
            service: django
        links:
            - redis
            - postgres
        entrypoint:
            - /scheduler-entrypoint.sh
        volumes:
            - ./docker/scheduler/data:/celerybeat
