apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: django-react-redis
  namespace: django-react
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: django-react-redis
    spec:
      containers:
      - name: redis
        image: redis:3.2.4
        imagePullPolicy: IfNotPresent
        ports:
        - name: redis
          containerPort: 6379
        volumeMounts:
        - mountPath: /var/lib/redis
          name: data
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: django-react-redis-storage
