apiVersion: v1
kind: Service
metadata:
  name: django-react-postgresql
  namespace: django-react
  labels:
    name: django-react-postgresql
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  selector:
    name: django-react-postgresql
