apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-react-config-storage
  namespace: django-react
  annotations:
    volume.beta.kubernetes.io/storage-class: fast
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mb
